// Copyright 2017-2023 @polkadot/hw-secux authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/hw-secux', path: 'auto', type: 'auto', version: '12.2.2-15-x' };
